export const staffinfo = [
    {
        name:'Diego',
        title:'Director',
        titleStyle:'yellow',
        phone:'1234567890',
        image:'hp-logo.png'
    },
    {
        name:'Mark',
        title:'Engineer',
        titleStyle:'blue',
        phone:'1234567890',
        image:'hp-logo.png'
    },
    {
        name:'Layla',
        title:'HR',
        titleStyle:'red',
        phone:'1234567890',
        image:'hp-logo.png'
    },
    {
        name:'Maya',
        title:'Sale',
        titleStyle:'purple',
        phone:'1234567890',
        image:'hp-logo.png'
    },
    {
        name:'Santi',
        title:'Director',
        titleStyle:'green',
        phone:'1234567890',
        image:'hp-logo.png'
    }
]